name: artisans_circle
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_bloc: ^9.0.0
  bloc: ^9.0.0
  meta: ^1.9.1
  equatable: ^2.0.5
  dio: ^5.7.0
  pretty_dio_logger: ^1.3.1
  http: ^1.2.1
  get_it: ^8.0.0
  freezed_annotation: ^2.4.1
  json_annotation: ^4.9.0
  google_fonts: ^6.2.1
  camera: ^0.10.0+1
  shared_preferences: ^2.0.0
  flutter_secure_storage: ^9.2.2
  cached_network_image: ^3.4.1
  google_sign_in: ^6.2.1
  sign_in_with_apple: ^6.1.0
  image_picker: ^1.1.2
  # url_launcher: ^6.3.1
  webview_flutter: ^4.8.0
  # image_cropper: ^5.0.1
  phone_numbers_parser: ^8.1.1
  package_info_plus: ^8.0.0
  share_plus: ^7.2.2
  firebase_core: ^3.4.0
  firebase_messaging: ^15.0.3
  cloud_firestore: ^5.4.4
  firebase_auth: ^5.2.0
  firebase_storage: ^12.3.2
  firebase_analytics: ^11.3.0
  firebase_crashlytics: ^4.1.0
  firebase_performance: ^0.10.0
  # firebase_remote_config: ^5.1.0
  # flutter_sound: ^9.28.0
  image_cropper: ^11.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  bloc_test: ^10.0.0
  mocktail: ^1.0.4
  build_runner: ^2.4.13
  freezed: ^2.5.7
  json_serializable: ^6.8.0
  http_mock_adapter: ^0.6.1
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  # Assets used by the app. Add actual image files under the assets/ directory.
  # If the images are not present the app will use the errorBuilder fallbacks added
  # to the widgets so the app won't crash. It's recommended to add the real images:
  #  - assets/google_logo.png
  #  - assets/logo.png
  assets:
    - assets/
    - assets/json/
    - assets/icons/
    - assets/icons/in_app_notif/
    - assets/images/
    - assets/audio/
    - assets/fonts/

  fonts:
    - family: Playfair Display
      fonts:
        - asset: assets/fonts/PlayfairDisplay-Regular.ttf
          weight: 400
        - asset: assets/fonts/PlayfairDisplay-Medium.ttf
          weight: 500
        - asset: assets/fonts/PlayfairDisplay-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/PlayfairDisplay-Bold.ttf
          weight: 700
    - family: Inter
      fonts:
        - asset: assets/fonts/inter/Inter_18pt-Regular.ttf
          weight: 400
        - asset: assets/fonts/inter/Inter_18pt-Medium.ttf
          weight: 500
        - asset: assets/fonts/inter/Inter_18pt-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/inter/Inter_18pt-Bold.ttf
          weight: 700
